package funwithcards;

import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;
import org.apache.commons.lang3.builder.ToStringBuilder;

public class Card implements Comparable<Card> {

    private Suite suite;
    private CardType cardType;

    public Card(Suite suite, CardType cardType) {
        this.suite = suite;
        this.cardType = cardType;
    }

    public Suite getSuite() {
        return suite;
    }

    public void setSuite(Suite suite) {
        this.suite = suite;
    }

    public CardType getCardType() {
        return cardType;
    }

    public void setCardType(CardType cardType) {
        this.cardType = cardType;
    }


    //Autogenerated these with apache builders
    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (obj == this) {
            return true;
        }
        if (obj.getClass() != getClass()) {
            return false;
        }
        Card rhs = (Card) obj;
        return new EqualsBuilder()
                .append(this.suite, rhs.suite)
                .append(this.cardType, rhs.cardType)
                .isEquals();
    }

    @Override
    public int hashCode() {
        return new HashCodeBuilder()
                .append(suite)
                .append(cardType)
                .toHashCode();
    }


    @Override
    public String toString() {
        return this.getCardType() + " of " + this.getSuite();
    }

    @Override
    public int compareTo(Card card) {
        if (this.suite == card.suite) {
            if (this.cardType == card.cardType) {
                return 0;
            }
            return this.cardType.getSortOrder() - card.cardType.getSortOrder();
        }

        return this.suite.getSortOrder() - card.suite.getSortOrder();
    }
}
